### ISSUE TITLE
Image environment completely reset in derived image

### ISSUE THREAD

**Issue by frederikbosch** [ironPeakServices/iron-alpine#19]
The variables set in this repository's image are not available anymore. This happened last few days. I guess commit c4e363ce46a81e0b2eac1aed1595bcfeedaf61ba is causing the problem. The problem is happening in my CI/CD builds but also local builds.

```Dockerfile
# no problem
FROM docker.pkg.github.com/ironpeakservices/iron-alpine/iron-alpine:3.11.0

# problem
FROM docker.pkg.github.com/ironpeakservices/iron-alpine/iron-alpine:3.11.3
FROM docker.pkg.github.com/ironpeakservices/iron-alpine/iron-alpine:3.11.5

RUN echo $CONF_DIR && echo $DATA_DIR && echo $APP_DIR && printenv
```

**Comment by hazcod** [comment]
Fixed in https://github.com/ironPeakServices/iron-alpine/commit/2d86377a8dec685d3ca34dfdb40d39cf0d7abeaa
Sorry for the issue! Can you try again?

**Comment by frederikbosch** [comment]
Fixed. Btw, I am testing all my images with [Goss](https://github.com/aelsabbahy/goss) and my goss.yml file looks as follows. It might be an idea to use it.

```yml
file:
  /app/conf:
    exists: true
    owner: app
    group: app
    mode: "0700"
  /app/data:
    exists: true
    owner: app
    group: app
    mode: "0700"

command:
  env_app_dir:
    exit-status: 0
    exec: "echo $APP_DIR"
    stdout:
      - /app
  env_conf_dir:
    exit-status: 0
    exec: "echo $CONF_DIR"
    stdout:
      - /app/conf
  env_data_dir:
    exit-status: 0
    exec: "echo $DATA_DIR"
    stdout:
      - /app/data
  pwd:
    exit-status: 0
    exec: "echo $PWD"
    stdout:
      - /app
```
